name: condominio_ui_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  keycloak_wrapper: ^1.4.6
  url_launcher: ^6.3.0
  crypto: ^3.0.2
  http: ^1.1.0
  web: ^1.1.1
  flutter_secure_storage: ^9.2.4
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_secure_storage_windows:
    path: third_party/flutter_secure_storage_windows

flutter:
  uses-material-design: true
